<template>
  <div id="app">
    <section>
      <button @click="isShown = !isShown">Toggle</button>
      <div v-if="isShown">
        <EventsSnakeGridResponsive
          :items="items"
        />
      </div>
    </section>
  </div>
</template>

<script>
import EventsSnakeGridResponsive from '@/components/EventsSnakeGridResponsive.vue'

const defaultItems = 
[	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "Together",
    "categories": [],
    "output": null,
    "path": "_events/jun-2022.md",
    "id": "/events/jun-2022",
    "relative_path": "_events/jun-2022.md",
    "url": "/events/jun-2022/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h2 id=\"tedxauckland-together\">TEDxAuckland <em>together</em></h2>\n",
    "draft": false,
    "layout": "event",
    "_schema": "default",
    "short_title": "JUN 2022",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":"https://tedxauckland.com/community/events#/june-2022/tickets/purchase"},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/web-page-banner-x3200-2.png",
    "tagline": "together",
    "start_date": "2022-06-08 00:00:00 +1200",
    "end_date": "2022-06-08 00:00:00 +1200",
    "address": "138 Halsey Street, Auckland 1010",
    "hide_speaker_names": false,
    "people": ["dallas-abel","ellen-joan-nelson","eric-renick","jim-lynch","will-hewitt"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone"],
    "supporting_partners": ["generator","halcyon-digital"],
    "event_partners": ["motuihe-group","jw-legal","sound_techniques","cloudcannon","qt-auckland","free-range-chef","good-george"],
    "carousel_images": [{"image":null,"alt":null}],
    "highlight_video_id": null,
    "youtube_playlist": null,
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": null,
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "jun-2022",
    "ext": ".md",
    "raw_content": "## TEDxAuckland *together*\n\nJoin us for TEDxAuckland *together*, a special evening event where five speakers will take centre stage. We're embracing 2022 with a sense of unity as we bring together ideas that will inspire us and showcase great speakers making the future better.\n\nWe'll be hosted by the gorgeous ASB Waterfront Theatre where the break will provide ample opportunities to meet fellow attendees, taste delicious food prepared by local Chefs, discuss the talks and make new connections.\n\nTickets are limited so be quick. Come alone, or bring a friend, either way let's get *together*.\n\n**WEDNESDAY 8th JUNE 2022**<br>**WATERFRONT THEATRE, WYNYARD QUARTER**\n\n#### Event Schedule\n\n4:00pm Registration Opens<br>5:00pm MC kicks off event<br>SESSION 1<br>*Break - Special meal*<br>SESSION 2 END 7:00pm<br>AFTER PARTY\\!\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "MAY 2021",
    "categories": [],
    "output": null,
    "path": "_events/may-2021.md",
    "id": "/events/may-2021",
    "relative_path": "_events/may-2021.md",
    "url": "/events/may-2021/",
    "tags": [],
    "collection": "events",
    "excerpt": "<p><em>Kia whakatōmuri te haere whakamua - ‘I walk backwards into the <strong>future</strong> with my eyes fixed on my <strong>past</strong>.’ - Māori Proverb.</em></p>\n",
    "draft": false,
    "layout": "event-may-2021",
    "_schema": "default",
    "short_title": "MAY 2021",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":"https://tedxauckland.com/community/events#/may-2021/tickets/purchase"},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/web-banner-1x3200.png",
    "tagline": "XXI",
    "start_date": "2021-05-22 00:00:00 +1200",
    "end_date": "2021-05-22 00:00:00 +1200",
    "address": "LIFE Central, 25 Normanby Road, Mount Eden, Auckland 1024",
    "hide_speaker_names": true,
    "people": ["greg-hart","kate-meyer","niva--yotam-kay","kaye-maree-dunn","matt-liggins","paul-adams","clive-elliott","claire-conza"],
    "flikr_galleries": ["https://www.flickr.com/photos/tedxauckland/albums/72157719581855291"],
    "major_partners": ["vodafone"],
    "supporting_partners": ["generator","countdown","halcyon-digital"],
    "event_partners": ["techweek2021","sound_techniques","cloudcannon","motuihe-group","life-venues","businessdesk","mamas-brew-shop","eighthirty","qt-auckland","jw-legal"],
    "carousel_images": [{"image":"/uploads/1-theme-desc---cover-x3200.png","alt":null},{"image":"/uploads/2-mind-map-x3200.png","alt":null},{"image":"/uploads/3-transition-x3200.png","alt":null},{"image":"/uploads/4-copy-x3200.png","alt":null},{"image":"/uploads/5-art-x3200.png","alt":null}],
    "highlight_video_id": null,
    "youtube_playlist": "https://youtube.com/playlist?list=PLcm2pIIAwlDsXWHfRGsy_eEONMKYMvjWN",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": null,
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "may-2021",
    "ext": ".md",
    "raw_content": "*Kia whakatōmuri te haere whakamua - ‘I walk backwards into the **future** with my eyes fixed on my **past**.’ - Māori Proverb.*\n\nTEDxAuckland 2021 is putting optimism centre stage with a offering of diverse speakers and ideas with the potential to change the World. Reset your thinking with ideas that can reshape the world for better.\n\nYou’ll experience incredible talks and performances during an immersive program. Extended breaks provide ample opportunities to meet fellow attendees, taste delicious food prepared by local Chefs, discuss the talks and meet speakers from this and previous events.\n\nJoin us at **TEDxAuckland 2021** as we emerge from 2020 and build a promising vision for the future at LIFE Central, Auckland's brand new, state of the art, purpose built convention centre.\n\nThe event is kid & child friendly\\! At the venue there will be staffed rooms for babies, toddlers and kids\\! Children under 10 free.\n\n\\#bethere\n\n**Venue:**&nbsp; &nbsp;[LIFE Central](https://lifenz.org/life-central/){: target=\"_blank\" rel=\"noopener\"}&nbsp; \\| &nbsp;25 Normanby Road, Mount Eden, Auckland 1024<br>**Time:**&nbsp; &nbsp; &nbsp; Starts at Midday\n\nE̶A̶R̶L̶Y̶ ̶B̶I̶R̶D̶ ̶$̶9̶9̶.̶0̶0̶\n\nN̶O̶R̶M̶A̶L̶ ̶B̶I̶R̶D̶ ̶$̶1̶4̶9̶.̶0̶0̶\n\nL̶A̶T̶E̶ ̶B̶I̶R̶D̶ ̶$̶1̶9̶9̶.̶0̶0̶\n\n### EVENT SCHEDULE\n\n* **11:30am Arrive & Register\\!**\n* **12:30pm MC kicks off event**\n* **SESSION 1**\n* [Matt Liggins](https://tedxauckland.com/people/matt-liggins/)\n* [Kate Meyer](https://tedxauckland.com/people/kate-meyer/)\n* [Greg Hart](https://tedxauckland.com/people/greg-hart/)\n* *Break 1 - Panel Discussion in breakout room*\n* **SESSION 2**\n* [Will Hewitt](https://tedxauckland.com/people/will-hewitt/)\n* [Clive Elliott](https://tedxauckland.com/people/clive-elliott/)\n* &nbsp;[Kaye-Maree Dunn](https://tedxauckland.com/people/kaye-maree-dunn/)\n* *Break 2 - Panel Discussion in breakout room*\n* **SESSION 3**\n* [Claire Conza](https://tedxauckland.com/people/claire-conza/)\n* [Paul Adams](https://tedxauckland.com/people/paul-adams/)\n* [Niva & Yotam Kay](https://tedxauckland.com/people/niva--yotam-kay/)\n* **END 4:45pm roughly…**\n\n##### &nbsp;\n\n# After Party\n\nCome join us at **the Chatham** in Victoria park for food, drinks and great banter.\n\n**The Chatham, 27 Drake Street, Victoria Park Market**\n\n&nbsp;\n\n&nbsp;\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "November 2020",
    "categories": [],
    "output": null,
    "path": "_events/november-2020.md",
    "id": "/events/november-2020",
    "relative_path": "_events/november-2020.md",
    "url": "/events/november-2020/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-november-2020\">TEDxAuckland November 2020</h1>\n",
    "draft": false,
    "layout": "event-nov-2020",
    "_schema": null,
    "short_title": "NOV 2020",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":"<iframe id=\"iframe-container\" src=\"https://events.humanitix.com/tedxauckland-2020/tickets?w=true&p=%23e62b1e\" width=\"100%\" height=\"600px\" frameborder=\"0\"></iframe>"},"application":{"active":false,"link":null}},
    "image": "/uploads/page-banner-3-x3200.png",
    "tagline": null,
    "start_date": "2020-11-14 00:00:00 +1300",
    "end_date": "2020-11-14 00:00:00 +1300",
    "address": "8 Henderson Valley Rd, Henderson, Auckland",
    "hide_speaker_names": null,
    "people": ["peter-gluckman","belinda-mckenzie","shalsee-vigeant","anderson-rocio","a-meditation-in-blackness"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone"],
    "supporting_partners": ["smales-farm"],
    "event_partners": ["whoa-studios","halcyon-digital","sound_techniques","brothers-beer","babich","good-herb-soda","qt-auckland","lowndes_jordan","ahi-restaurant","the-grounds","know-your-food"],
    "carousel_images": [{"image":"/uploads/1-THEME DESC - COVER150.png","alt":"theme slideshow image"},{"image":"/uploads/2-MIND MAP150.png","alt":"theme slideshow image"},{"image":"/uploads/3-INTRO150.png","alt":"theme slideshow image"},{"image":"/uploads/4-FIRST TRANSLATIONS150.png","alt":"theme slideshow image"},{"image":"/uploads/5-X AS A CONCEPT150.png","alt":"theme slideshow image"},{"image":"/uploads/6-SIMPLIFICATION150.png","alt":"theme slideshow image"},{"image":"/uploads/8-THEME ICON150.png","alt":"theme slideshow image"},{"image":"/uploads/9-FINAL150.png","alt":"theme slideshow image"}],
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDsrmFhE9IJKd02YFGgYqsZv",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": null,
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "november-2020",
    "ext": ".md",
    "raw_content": "# TEDxAuckland November 2020\n\n**TEDxAuckland** is back at Whoa\\! Studios and The Grounds. Get ready for an exceptional confluence of ideas, networking, and culinary experience (and of course the famous after-party).\n\nEvery year typically has a few defining moments, but 2020 has outdone itself. It’s been a year of world-changing, paradigm-shifting developments\\! With a pandemic still raging and waves of social change swelling around the globe, there’s still a lot of history left to be made in 2020.\n\nJoin the conversation, as we make history - and make sense of it. We’ll be one of the very few, live in person TEDx events taking place in the world and we’d love you to be part of it.\n\nWe’ll be hosted by Whoa\\! Studios in Henderson with an exceptional dining experience by multi-award winning Kiwi chef&nbsp;[Ben Bayly](https://benbayly.co.nz) of [The Grounds](https://thegrounds.co.nz) and [Ahi Restaurant](https://www.ahirestaurant.co.nz).\n\nWe have an incredible line up of 5 speakers and a 4 course dinner. With only 150 places available, get in quick to be a part of it.\n\nJoin us at Whoa\\! Studios on Saturday 14th November 2020 for a night you’ll never forget in a year you’d like to forget.\n\n**Timetable**<br>4:30pm - Guests to arrive at Whoa\\! Studios greeted with drinks<br>5:30pm - 6:45pm TEDxAuckland 2020<br>Anderson Rocio -&nbsp;*Performance*<br>Shalsee Vigeant<br>Sir Peter Gluckman<br>Belinda McKenzie<br>A meditation in blackness -&nbsp;*Performance*\n\n7pm - 10pm: Dinner & Drinks\n\nWhoa\\! Studios + The Grounds location:&nbsp;[https://goo.gl/maps/b6FZcC2mN6D2E3iW9](https://goo.gl/maps/b6FZcC2mN6D2E3iW9)\n\n**Menu matched with Wine or Beer**<br>*Round 1*<br>Dairy Flat goats fromage frais<br>Organic asparagus w fennel jam & cropper tomatoes\n\n*Round 2*<br>Scampi Corn dogs w Jo-Bros original sauce<br>[Koura](https://www.koruafood.com) Wagyu tartare with [Ahi](https://www.ahirestaurant.co.nz) hot sauce, nasturtium, crispy agria & bull kelp salt\n\n*Round 3*<br>[Jo-Bros](https://www.jobrosburgers.com) x [Korua](https://www.koruafood.com) Wagyu Burger\n\n*Round 4*<br>Strawberry & elderflower TEDx magnum gelato with passionfruit pavlova\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "tūmanako: Nov 2019",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-tūmanako.md",
    "id": "/events/tedxauckland-tūmanako",
    "relative_path": "_events/tedxauckland-tūmanako.md",
    "url": "/events/tumanako/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-november-2019\">TEDxAuckland November 2019</h1>\n",
    "draft": false,
    "layout": "event-tumanako",
    "_schema": null,
    "short_title": "tūmanako: Nov 2019",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":"https://tedxauckland.com/community/events#/tumanako/buy-tickets"}},
    "image": "/uploads/tumanako-theme.svg",
    "tagline": null,
    "start_date": "2019-11-16 00:00:00 +1300",
    "end_date": "2019-11-16 00:00:00 +1300",
    "address": "138 Halsey St, Auckland CBD, Auckland",
    "hide_speaker_names": null,
    "people": ["brianna-fruean","thomas-owen","dmitry-selitskiy","kris-gledhill","simon-che-de-boer","sonya-renee-taylor","scenes-from-a-yellow-peril","rose-northey","angela-lim","andrea-reid","annamarie-jamieson","max-rashbrooke","tony-fernando","getrude-matshe-kanicki"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone"],
    "supporting_partners": ["bizdojo","bnz"],
    "event_partners": ["lowndes_jordan","cloudcannon","halcyon-digital","sound_techniques","white-studios","allpress","blue-star","wear"],
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDtVUwKpkWM0Fwl7GNNVkSpA",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/tumanako/",
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "tedxauckland-tūmanako",
    "ext": ".md",
    "raw_content": "# TEDxAuckland November 2019\n\n*tūmanako*\\: to hope for a better future\n\nTEDxAuckland is taking over 'ASB Waterfront Theatre' for a full day of talks, performances, inspiration, and new connections.\n\nThe event is fully catered so just bring your lovely self and maybe someone else\\!\n\nFind the growing list of speakers below.\n\n~~Early Bird tickets $99<br>General Release tickets $129~~<br>~~Late Bird $159~~\n\n**When:** Saturday 16 November 2019, midday - 5:30pm\n\nDoors & registration opens at 10:30am<br><br>**Where:** ASB Waterfront Theatre\n",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "IN THE DARK",
    "categories": [],
    "output": null,
    "path": "_events/dining-in-the-dark.md",
    "id": "/events/dining-in-the-dark",
    "relative_path": "_events/dining-in-the-dark.md",
    "url": "/events/08-2019/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"introducing-a-world-first\">Introducing A World First</h1>\n",
    "draft": false,
    "layout": "event-dark",
    "_schema": null,
    "short_title": "AUG 2019 IN THE DARK",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":"https://tedxauckland.com/community/events#/dark-2019/apply"}},
    "image": "/uploads/dining-in-the-dark.png",
    "tagline": "hear you there ...",
    "start_date": "2019-08-31 00:00:00 +1200",
    "end_date": "2019-08-31 00:00:00 +1200",
    "address": null,
    "hide_speaker_names": null,
    "people": ["cassie-roma","vincent-vuillard"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone-dark"],
    "supporting_partners": ["bizdojo-dark"],
    "event_partners": ["lowndes_jordan","halcyon-digital","white-studios","dans-le-noir-","fuzed-printing"],
    "carousel_images": null,
    "highlight_video_id": "-mmHQJRe5AU",
    "youtube_playlist": "PLcm2pIIAwlDtyjdpbf6_poIqv8w-fEbxc",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/08-2019/",
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "dining-in-the-dark",
    "ext": ".md",
    "raw_content": "# Introducing A World First\n\nOn August 31st, TEDxAuckland is hosting a Salon event which will be the first TEDx event in the world to be held in **complete darkness**.\n\nHosted by Dans le Noir ? Rydges Auckland and shared with you by Vodafone NZ - this will be an unforgettable experience like no other.\n\n#### TEDxAuckland and Dans le Noir ? are combining to provide you with a unique sensory, social and human experience.\n\n**A Sensory Journey:** Dining in absolute darkness is a sensory experience that awakens senses and enables guests to completely re-evaluate their perception of taste and smell.\n\n**A Place to Socialise:** Darkness eradicates shyness & erases preconceptions. Communication becomes more intense, authentic and spontaneous. Both with the people you sit with, and the TEDxAuckland speakers.\n\n**A Unique Human Experience:** Blind people work not only as waitstaff but also as guides during this experience. Reversing roles, the guide becomes patrons’ eyes for the time of the dinner\\!\n\n#### Event Information:\n\n* Enjoy a three course meal, with 3 different menu versions freshly created for this experience.\n* 2x Speakers will present in pitch black between meal courses.\n* Just like the food, information about the speakers has been hidden so attendee's go into the event with zero preconceptions.\n* **When**\\: Saturday August 31st starting 6pm till late.\n* **Where**\\: Dans le Noir ? Rydges Auckland.\n* **Price**\\: $199.\n* The event will be followed by an afterparty at The Glass Goose.\n\nIf you would like to attend, you will need to register at the link below. Spaces are extremely limited, so make sure to get in quick.\n",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "May 2019 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2019-05.md",
    "id": "/events/tedxauckland-2019-05",
    "relative_path": "_events/tedxauckland-2019-05.md",
    "url": "/events/05-2019/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-may-2019\">TEDxAuckland May 2019</h1>\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "May 2019",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/tedx-whoa-banner-2-3600x.png",
    "tagline": null,
    "start_date": "2019-05-01 00:00:00 +1200",
    "end_date": "2019-05-01 00:00:00 +1200",
    "address": "8-14 Henderson Valley Rd, Henderson, Auckland",
    "hide_speaker_names": null,
    "people": ["james-hurman","rashina-hoda","chris-smith"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone"],
    "supporting_partners": ["bizdojo"],
    "event_partners": ["lowndes_jordan","halcyon-digital","misfit-brewing-co-","whoa-studios","the-grounds","babich","white-studios"],
    "carousel_images": null,
    "highlight_video_id": "sDgL_9RbDrs",
    "youtube_playlist": "PLcm2pIIAwlDu5hg5mkxbHFesUIMgFGyYz",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/05-2019/",
    "seo": {"name":"TEDxAuckland","type":"Event","links":[null]},
    "slug": "tedxauckland-2019-05",
    "ext": ".md",
    "raw_content": "# TEDxAuckland May 2019\n\nIn 2019, TEDxAuckland reaches its 10th year of celebrating ideas, innovation and inspiration. So to celebrate we’re holding not one but multiple events around Auckland\\!\n\nOur first event on **May 1st** will host 5 amazing speakers at **Whoa\\! Studios** - a state of the art studio and theatre that produces numerous New Zealand and international films, television and stage productions.\n\nAfter the event, all attendees will socialise with our speakers at the inclusive dinner in The Grounds Eatery. This four-course shared dinner, accompanied with wine and drinks, will be orchestrated by the acclaimed and multi-award winning Kiwi chef, Ben Bayly, conjuring it up with local produce from West Auckland.\n\nThere are only 160 seats available for this more intimate experience, so make sure to register your interest quickly. Tickets are $139. **Update**\\: **Sold out\\!**\n\n**Timetable for the event:**\n\n5pm-5:30pm: Guests to arrive at Whoa\\! Studios<br>6pm-7pm: Speaker talks<br>7pm-10pm: Dinner & Drinks\n\n**Whoa\\! Studios + The Grounds location**\\:\n\n[https://goo.gl/maps/b6FZcC2mN6D2E3iW9](https://goo.gl/maps/b6FZcC2mN6D2E3iW9){: target=\"_blank\"}\n\n&nbsp;\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2018 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2018.md",
    "id": "/events/tedxauckland-2018",
    "relative_path": "_events/tedxauckland-2018.md",
    "url": "/events/2018/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-2018\">TEDxAuckland 2018</h1>\n",
    "draft": false,
    "layout": "event-2018",
    "_schema": null,
    "short_title": "2018",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/tedx-auckland-2018-banner-3.1.jpg",
    "tagline": "Off Piste",
    "start_date": "2018-10-13 00:00:00 +1300",
    "end_date": "2018-10-13 00:00:00 +1300",
    "address": "Shed 10, 89 Quay Street, Queens Wharf, Auckland 1010",
    "hide_speaker_names": null,
    "people": ["hemi-kelly","fraser-mcconnell","richie-hardcore","grace-stratton","pete-ceglinski","katie-williams","jazz-thornton","sarah","swee-tan","imche-fourie","zeshan-qureshi","pania-newton","israel-izzy-whitley","david-downs","daniel-gudsell","eliot-witters","aaja-nachle","jess-quinn","andrew-barnes","imugi"],
    "flikr_galleries": [null],
    "major_partners": ["vodafone"],
    "supporting_partners": ["bizdojo"],
    "event_partners": ["pro-live-tv","lowndes_jordan","iticket","marvel-grill","korua","lectrosonics","lotech","sound_techniques","stopmo","wear","cloudcannon","allpress"],
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDutXJI4AWeUPpEmBZCIF2ry",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2018/",
    "seo": {"name":"TEDxAuckland 2018 - Off Piste","type":"Event","links":["https://www.facebook.com/events/629283860774532","https://www.iticket.co.nz/events/2018/oct/tedxauckland-2018"]},
    "slug": "tedxauckland-2018",
    "ext": ".md",
    "raw_content": "# TEDxAuckland 2018\n\nIn 2018, TEDxAuckland's annual festival of ideas is returning to **Shed 10** on **October 13th**. This year will see speakers from New Zealand and around the globe come together for a day of inspiration and connection in the heart of Auckland City.\n\n#### Off-Piste: Adjective, adverb.\n\n1. Away from prepared ski runs.\n2. So as to deviate from what is conventional, usual, or expected.\n3. An unsupervised, ungroomed, and unmarked area.\n\nSpeakers, performers, food vendors, and event details to be announced here and on [facebook](https://www.facebook.com/events/629283860774532){: target=\"_blank\"} in the coming weeks.\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2017 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2017.md",
    "id": "/events/tedxauckland-2017",
    "relative_path": "_events/tedxauckland-2017.md",
    "url": "/events/2017/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-2017\">TEDxAuckland 2017</h1>\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2017",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/tedxakl-2017-banner-fw.png",
    "tagline": null,
    "start_date": "2017-12-01 00:00:00 +1300",
    "end_date": "2017-12-02 00:00:00 +1300",
    "address": "Aotea Centre, 50 Mayoral Drive Auckland Central Auckland 1010",
    "hide_speaker_names": true,
    "people": ["andy-crowe--rui-peng","alexander-macdonald","angie-judge","anna-faber","cameron-sims","cather-simpson","chris-pemberton","david-razowsky","emeline-paat-dahlstrom","jahra-rager-wasasala","juliet-arnott","liam-malone","lisa-king","mai-chen","michael-corballis","nigel-parker","pete-bethune","sam-stubbs","shaveer-mirpuri","william-watson","yoseph-ayele"],
    "flikr_galleries": ["72157690330288051","72157662372094117","72157690330455751","72157690330728971","72157664411957938"],
    "major_partners": ["nib"],
    "supporting_partners": ["u-s-embassy","auckland-live"],
    "event_partners": ["allpress","bean-boy","fair_food","fine_and_dandy","fonterra","forage_bloom","forbidden_cider","giapo","howick_and_eastern_bus","hypermedia","innocent_packaging","judge_bao","kiwit","korua","lotech","lweis_road_creamery","mainland","niwa-colour","no1","oracle","pallet-kingdom","phosphor","print_management","ralphie","sharesies-love-investing","stopmo","superbher","tigerburgeryum","vinomofo","waiheke-herbs","whova-logo-box","wiseboy","bird-on-a-wire","ben-and-jerry","little_bird","fairtrade","as-colour"],
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDtn58jNUEqyRUgUuNJ8Qjdd",
    "other_youtube_playlist_title": "EDxMini's",
    "other_youtube_playlist": "PLcm2pIIAwlDv8TaGu92limqVEmJN6q7eb",
    "permalink": "/events/2017/",
    "seo": {"name":"TEDxAuckland 2017","type":"Event"},
    "slug": "tedxauckland-2017",
    "ext": ".md",
    "raw_content": "# TEDxAuckland 2017\n\nThis year we’re back at the Aotea Centre for our 2nd multi-day festival. Join us for 21 talks from local and international speakers, food, fun and partner activations.\n\nTEDxAuckland is an Ideas Festival. Get ready to be inspired and challenged by local and international people changing the world with their unique ideas, and in the breaks get chatting to the equally incredible attendees around you\\!\n\nFood and drink during the event is included in your Multi-Day Pass and on Saturday evening, once the talks are done, another experience awaits VIP ticket holders.\n\n#### The Program\n\nThe Festival opens at 3pm Friday for registrations and activations. The first talks start at 5.00pm through to 7pm.\n\nThe Friday night Burger Banquet is made by: Tiger Burger / Wise Boys / Judge Bao / Ralphs / Bird on a wire\n\nOn Saturday the Festival opens at 9.30am with the first talks beginning at 10am.<br>Lunch on Saturday is made by Eat My Lunch, thanks to Fonterra.\n\nThe talks will conclude around 5pm on Saturday. Those attending the sold out VIP SocialDinner will jump on a bus (provided) for a 5 course dinner produced by some amazing local chefs. Matched with local beer and wine.\n\nThose keen to kick on are invited to join TEDx crew, speakers and friends at Sweat Shop Brew Kitchen, Sale St, Freemans Bay after 9pm.\n\n&nbsp;\n",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2016 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2016.md",
    "id": "/events/tedxauckland-2016",
    "relative_path": "_events/tedxauckland-2016.md",
    "url": "/events/2016/",
    "tags": [],
    "collection": "events",
    "excerpt": "<h1 id=\"tedxauckland-2016\">TEDxAuckland 2016</h1>\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2016",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/flipside-banner.jpg",
    "tagline": "flipside",
    "start_date": "2016-05-05 00:00:00 +1200",
    "end_date": "2016-05-06 00:00:00 +1200",
    "address": "Shed 10, 89 Quay Street, Queens Wharf, Auckland 1010",
    "hide_speaker_names": null,
    "people": ["barbara-breen","ian-mccrae","lizzie-marvelly","jayne-bailey","cori-gonzalez-macuer","adrien-taylor","mike-moka","anna-coddington","toby-carr","james-bergin","vaughan-rowsell","grace-clapham--solonia-teodros","jess-holly-bates","samuel-gibson","georgia-lala","richard-aston","pani-farvid","sharad-paul","minnie-barragwanath","richard-little","david-harvey","matt-shirtcliffe","keith-ng","rory-steyn","modern-māori-quartet"],
    "flikr_galleries": ["72157666367306513","72157668777484451"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDvHTuiHHEln6B809w-3wV2V",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2016/",
    "seo": {"name":"TEDxAuckland 2016","type":"Event"},
    "slug": "tedxauckland-2016",
    "ext": ".md",
    "raw_content": "# TEDxAuckland 2016\n\n2016 TEDxAuckland was a little different. We curated ideas for a global audience; global in their diversity, expertise and residence. Say hello to TEDxAuckland 2016!\n\n#### Our Theme this year is: *flipside*\n\n* The perspective you get from seeing an old problem in a new way.\n* Turning hierarchies on their head and putting ideas ahead of ideology.\n* Sidestepping power structures, gender, race and geography.\n* Stepping outside your workplace, your country and even your hemisphere to connect with a community of speakers, delegates and partners united by a healthy disrespect for business as usual.\n\nThe event featured ideas and talks from amazing people changing the world. We’ll be matching the diversity of ideas with an equally diverse audience, you!\n\nTEDxAuckland 2016: *flipside* featured talks over two days, events, activities and social time. Shed 10 the venue provided the perfect space for hosting, break out spaces and food and beverage side you deserve.\n\n[See the 2016 FoodStory Video.](https://www.youtube.com/watch?v=J0s-ob4FGcg)\n",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2015 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2015.md",
    "id": "/events/tedxauckland-2015",
    "relative_path": "_events/tedxauckland-2015.md",
    "url": "/events/2015/",
    "tags": [],
    "collection": "events",
    "excerpt": "\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2015",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/2015banner2.png",
    "tagline": null,
    "start_date": "2015-05-02 00:00:00 +1200",
    "end_date": "2015-05-02 00:00:00 +1200",
    "address": "Victory Convention Centre, 98 Beaumont Street, Auckland Central, Auckland 1010",
    "hide_speaker_names": null,
    "people": ["siouxsie-wiles","grant-schofield","riley--steve-hathaway","steve-pointing","hong-sheng-chiong","tom-scott","gavin-healy","billie-jordan","the-hip-op-eration-crew","dale-pfeifer","janette-searle","sir-bob-harvey","tame-iti","max-cryer"],
    "flikr_galleries": ["72157653020465246","72157654429408953","72157653487162285","72157651989131684"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDvRoXJiHdo6KFJXMHPWzzrd",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2015/",
    "seo": {"name":"TEDxAuckland 2015","type":"Event"},
    "slug": "tedxauckland-2015",
    "ext": ".md",
    "raw_content": "",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2014 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2014.md",
    "id": "/events/tedxauckland-2014",
    "relative_path": "_events/tedxauckland-2014.md",
    "url": "/events/2014/",
    "tags": [],
    "collection": "events",
    "excerpt": "<p>TEDxAuckland 2014 took place at the Aotea Centre on Saturday 16th August. <em>Ascending</em> was the overriding theme for TEDxAuckland 2014. The day was packed with over 16 speakers, musical acts and an after party.</p>\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2014",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": null,
    "tagline": "Ascending",
    "start_date": "2014-08-16 00:00:00 +1200",
    "end_date": "2014-08-16 00:00:00 +1200",
    "address": "Aotea Centre, 50 Mayoral Drive Auckland Central Auckland 1010",
    "hide_speaker_names": null,
    "people": ["luke-nola","muskan-devta","urzila-carlson","mike-allsop","rachel-callander","vivien-maidaborn","matt-stone","rebecca-mills","catherine-bell","john-boone","riley-elliott","richard-easther","david-downs--jon-bridges","vaughan-rowsell","sarah-longbottom","rebecca-wadey","waikare-komene","mohamed-hassan"],
    "flikr_galleries": ["72157656140582479","72157656599694255","72157656734991456","72157656389115760"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDuTR1f_L4RvqDinFjibiqDc",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2014/",
    "seo": {"name":"TEDxAuckland 2014","type":"Event"},
    "slug": "tedxauckland-2014",
    "ext": ".md",
    "raw_content": "TEDxAuckland 2014 took place at the Aotea Centre on Saturday 16th August. *Ascending* was the overriding theme for TEDxAuckland 2014. The day was packed with over 16 speakers, musical acts and an after party.\n\nTheme<br>*Ascending* is about individuals and society rising to a higher level of consciousness.\n\n*Ascending* is about finding the positives in any situation and building on them to make our lives, community, business and planet better.",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2013 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2013.md",
    "id": "/events/tedxauckland-2013",
    "relative_path": "_events/tedxauckland-2013.md",
    "url": "/events/2013/",
    "tags": [],
    "collection": "events",
    "excerpt": "\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2013",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": "/uploads/20130803-tedx-georgias-high-77.jpg",
    "tagline": "convergemerge",
    "start_date": "2013-08-03 00:00:00 +1200",
    "end_date": "2013-08-03 00:00:00 +1200",
    "address": "Aotea Centre, 50 Mayoral Drive Auckland Central Auckland 1010",
    "hide_speaker_names": null,
    "people": ["jimi-hunt","lillian-grace","david-trubridge","pete-russell","grace-taylor","malcolm-rands","joseph-michael","helen-clark","robert-oliver","richard-faull","ash-graham","brian-sweeney","sophie-tamati","welby-ings","robyn-paterson","dale-williams"],
    "flikr_galleries": ["72157656765142439","72157656607912019","72157641143953353"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDsT31BlI19NifrQ9GDUwUuT",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2013/",
    "seo": {"name":"TEDxAuckland 2013","type":"Event"},
    "slug": "tedxauckland-2013",
    "ext": ".md",
    "raw_content": "",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2012 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2012.md",
    "id": "/events/tedxauckland-2012",
    "relative_path": "_events/tedxauckland-2012.md",
    "url": "/events/2012/",
    "tags": [],
    "collection": "events",
    "excerpt": "\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2012",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": null,
    "tagline": null,
    "start_date": "2012-10-06 00:00:00 +1300",
    "end_date": "2012-10-06 00:00:00 +1300",
    "address": "Aotea Centre, 50 Mayoral Drive Auckland Central Auckland 1010",
    "hide_speaker_names": null,
    "people": ["michelle-dickinson","andrew-patterson","david-krofcheck","assil-russell","pip-hall","paul-wood","john-windsor","alistair-knott","sam-hunt","emma-rogan","aakash-polra--jade-tan","sean-gourley","philip-patston","victoria-spackman","matthew-simmons","paul-cameron","peter-young"],
    "flikr_galleries": ["72157641139177714","72157641143525304"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDtgZg-UX4afZg-Y5z_9Yk3h",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2012/",
    "seo": {"name":"TEDxAuckland 2012","type":"Event"},
    "slug": "tedxauckland-2012",
    "ext": ".md",
    "raw_content": "",
    "is_highlighted": false,
    "event_listing": {"is_highlighted":false,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2010 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2010.md",
    "id": "/events/tedxauckland-2010",
    "relative_path": "_events/tedxauckland-2010.md",
    "url": "/events/2010/",
    "tags": [],
    "collection": "events",
    "excerpt": "\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2010",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": null,
    "tagline": "Ideas Worth Doing",
    "start_date": "2010-09-26 00:00:00 +1200",
    "end_date": "2010-09-26 00:00:00 +1200",
    "address": "Westlake Boys High School, 30 Forrest Hill Road, Forrest Hill, Auckland 0620",
    "hide_speaker_names": null,
    "people": ["richard-loseby","one-beep","stephen-knightly","divya-dhar","julie-bartlett","jonathan-milne","kate-smith","privahini-bradoo"],
    "flikr_galleries": ["72157641137952633"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLcm2pIIAwlDt91h9DBqsgz7F6y7Q5kW7Y",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2010/",
    "seo": {"name":"TEDxAuckland 2010","type":"Event"},
    "slug": "tedxauckland-2010",
    "ext": ".md",
    "raw_content": "",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	},
	
	{
    "date": "2022-08-18 19:26:51 +1200",
    "title": "2009 event",
    "categories": [],
    "output": null,
    "path": "_events/tedxauckland-2009.md",
    "id": "/events/tedxauckland-2009",
    "relative_path": "_events/tedxauckland-2009.md",
    "url": "/events/2009/",
    "tags": [],
    "collection": "events",
    "excerpt": "\n",
    "draft": false,
    "layout": "event",
    "_schema": null,
    "short_title": "2009",
    "upcoming": false,
    "ticket_sales": {"link":{"active":false,"src":null},"embed":{"active":false,"code":null},"application":{"active":false,"link":null}},
    "image": null,
    "tagline": null,
    "start_date": "2009-11-05 00:00:00 +1300",
    "end_date": "2009-11-05 00:00:00 +1300",
    "address": "Westlake Boys High School, 30 Forrest Hill Road, Forrest Hill, Auckland 0620",
    "hide_speaker_names": null,
    "people": ["michael-henderson","wendy-mcguinness","nigel-parker","robin-kelly","brenda-frisk","kaila-colbin","scott-gilmour","glen-compain","billy-gammon","andy-blood","ray-avery"],
    "flikr_galleries": ["72157641137766674"],
    "major_partners": null,
    "supporting_partners": null,
    "event_partners": null,
    "carousel_images": null,
    "highlight_video_id": null,
    "youtube_playlist": "PLDA6216FD76A6083C",
    "other_youtube_playlist_title": null,
    "other_youtube_playlist": null,
    "permalink": "/events/2009/",
    "seo": {"name":"TEDxAuckland 2009","type":"Event"},
    "slug": "tedxauckland-2009",
    "ext": ".md",
    "raw_content": "",
    "is_highlighted": true,
    "event_listing": {"is_highlighted":true,"description":null,"image":"/uploads/default-speaker-photo.jpg"},
	}
	
]


export default {
  name: 'events-snake-grid-scaffold',

  components: {
    EventsSnakeGridResponsive,
  },

  methods: {
  },
  mounted() {
  },
  beforeDestroy() {
  },
  data() {
    return {
      items: defaultItems,
      baseUrl: process.env.BASE_URL,
      isShown: true,
    }
  },

  computed: {
  }
}

</script>

<style scoped>
</style>
